export const SAVE_COLLECTIONS = "SAVE_COLLECTIONS";
export const SAVE_COLLECTION = "SAVE_COLLECTION";
export const DELETE_COLLECTION = "DELETE_COLLECTION";
export const TOGGLE_FAVOURITE = "TOGGLE_FAVOURITE";
